routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('addProduct','ProductController@create');
//Route::post('storeProduct','ProductController@store');

Route::resource('products','ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Validator;

class Product extends Model
{

    protected $table = "crm_addresses";
    protected $guarded = ['id', '_token'];

    protected $fillable = ['name','description','price'];
    protected $perPage = 30;

    protected $file_name = "product.json";

    public function writeToJson($data){
        if(Storage::has($this->file_name)){
            $inp = Storage::get($this->file_name);
            $tempArray = json_decode($inp,true);


            $tempArray[] =$data;
            $jsonData = json_encode($tempArray);
            Storage::put($this->file_name, $jsonData);
        }else{
            $dataArr = [];
            $dataArr[] = $data;
            Storage::put($this->file_name,json_encode($dataArr));
        }

        return true;


    }

    public function getJson(){
        $inp = Storage::get($this->file_name);

        return $inp;
    }

    public function validateProduct($fields){
        return $validator = Validator::make($fields, [
            'name' => 'required|string',
            'quantity' => 'required|numeric',
            'price' => 'required|numeric'
        ]);


    }

    public function getProductValidationResponse($messages){
        $messageStack = [];

        foreach ($messages as $message){
            foreach ($message as $m){
                $messageStack[] = $m;
            }
        }

        return $messageStack;
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;
use Validator;

class ProductController extends Controller
{
    /**
     * Initailizes Dependencies and init variables
     *
     *
     */
    public function __construct(Product $product)
    {
        $this->product = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("alt-product-ajax");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("product-ajax");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = $this->product->validateProduct($request->all());
        if ($validator->fails()) {
            //dd($validator->messages()->toArray());
            $message["error"] = $this->product->getProductValidationResponse($validator->messages()->toArray());
            return response()->json($message,422);

        }

        try{
            $resData = $request->except('_token');

            //writes to Json file
            $this->product->writeToJson($resData);

            //get Json content from file
            $jsonFile = $this->product->getJson();
            //dd($jsonFile);
            //return response()->json(json_decode($jsonFile));
            return response()->json($resData,200);
        }catch (FileNotFoundException $e){
            Log::error($e->getMessage());
            abort(500);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

resources/views/ajax-master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <meta name="csrf-token" content="{{csrf_token()}}">
    <!-- Website CSS style -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

    <style>
        /*
/* Created by Filipe Pina
 * Specific styles of signin, register, component
 */
        /*
         * General styles
         */
        #playground-container {
            height: 500px;
            overflow: hidden !important;
            -webkit-overflow-scrolling: touch;
        }
        body, html{
            height: 100%;
            background-repeat: no-repeat;
            background:url(https://i.ytimg.com/vi/4kfXjatgeEU/maxresdefault.jpg);
            font-family: 'Oxygen', sans-serif;
            background-size: cover;
        }

        .main{
            margin:50px 15px;
        }

        h1.title {
            font-size: 50px;
            font-family: 'Passion One', cursive;
            font-weight: 400;
        }

        hr{
            width: 10%;
            color: #fff;
        }

        .form-group{
            margin-bottom: 15px;
        }

        label{
            margin-bottom: 15px;
        }

        input,
        input::-webkit-input-placeholder {
            font-size: 11px;
            padding-top: 3px;
        }

        .main-login{
            background-color: #fff;
            /* shadows and rounded borders */
            -moz-border-radius: 2px;
            -webkit-border-radius: 2px;
            border-radius: 2px;
            -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);

        }
        .form-control {
            height: auto!important;
            padding: 8px 12px !important;
        }
        .input-group {
            -webkit-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
            -moz-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
            box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
        }
        #button {
            border: 1px solid #ccc;
            margin-top: 28px;
            padding: 6px 12px;
            color: #666;
            text-shadow: 0 1px #fff;
            cursor: pointer;
            -moz-border-radius: 3px 3px;
            -webkit-border-radius: 3px 3px;
            border-radius: 3px 3px;
            -moz-box-shadow: 0 1px #fff inset, 0 1px #ddd;
            -webkit-box-shadow: 0 1px #fff inset, 0 1px #ddd;
            box-shadow: 0 1px #fff inset, 0 1px #ddd;
            background: #f5f5f5;
            background: -moz-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f5f5f5), color-stop(100%, #eeeeee));
            background: -webkit-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
            background: -o-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
            background: -ms-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
            background: linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f5f5f5', endColorstr='#eeeeee', GradientType=0);
        }
        .main-center{
            margin-top: 30px;
            margin: 0 auto;
            max-width: 400px;
            padding: 10px 40px;
            background:#009edf;
            color: #FFF;
            text-shadow: none;
            -webkit-box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);
            -moz-box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);
            box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);

        }
        span.input-group-addon i {
            color: #009edf;
            font-size: 17px;
        }

        .login-button{
            margin-top: 5px;
        }

        .login-register{
            font-size: 11px;
            text-align: center;
        }

    </style>

    <title>Admin</title>
</head>
<body>
@yield("content")
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Include all compiled plugins (below), or include individual files as needed -->
{{--<script src="js/bootstrap.min.js"></script>--}}
</body>
</html>

resources/views/alt-ajax-master.blade.php
<html>
<head>
    <title>Product</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

</head>
<body>

@yield("content")
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>




<script>

    $(document).ready(function() {
        $.ajax({
            url: "{{route('products.index')}}",
            type: 'get',
            dataType: 'json',
            success: function (data) {
                $.each(data, function (k,v) {
                    $("#mydata").append("<tr><td>"+v.name+"</td><td>"+v.quantity+"</td><td>"+v.price+"</td></tr>");
                });
                console.log(data);
            }

        });
    });

    $("form#product_add").submit(function () {
        event.preventDefault();
        var data = $("#product_add").serializeArray();
        var jdata = {};
        for (var i = 0; i < data.length; i++) jdata[data[i].name] = data[i].value;
        this.reset();
        view ='';

        $.ajax({
            url: "{{route('products.store')}}",
            headers: {
                'X-CSRF-TOKEN': "{{csrf_token()}}"
            },
            type: 'post',
            dataType: 'json',
            data: jdata,
            success: function (data) {
                console.log(data.error);
//                if(){
//
//                }

                $("#mydata").append("<tr><td>"+data.name+"</td><td>"+data.quantity+"</td><td>"+data.price+"</td></tr>");
                console.log(data);
            },
            error: function (xhr) {
                if(xhr.status==422) {
                    $('#errormessage').html("");
                    $.each(JSON.parse(xhr.responseText), function (k, v) {
                        $.each(v, function (key, value) {
                            $('#errormessage').append('<p style="color:red">' + value + '</p>');

                        })
                        console.log(view);
                    });
                }else if(xhr.status==501){
                    console.log(xhr.responseText);
                    $.each(JSON.parse(xhr.responseText), function (k, v) {
                        $('#errormessage').html(v[0]);
                    });
                } else if(xhr.status==500)
                    $('#errormessage').html("server error");

            }

        });

        return false;
    });

</script>

</body>
</html>

resources/views/alt-product-ajax.blade.php
@extends("alt-ajax-master")
@section("content")
    <div class="container">

        <div class="row">

            <div class="col-lg-8 col-lg-offset-2">

                <h1>Products</h1>

                <p class="lead">This is a demo app with Laravel PHP and AJAX.</p>

                <form id="product_add">

                    <div class="messages" id="errormessage"></div>

                    <div class="controls">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_name">Product name *</label>
                                    <input id="form_name" type="text" name="name" class="form-control" placeholder="Please enter name of the product *"  data-error="Product name is required.">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_quantity">Quantity *</label>
                                    <input id="form_quantity" type="text" name="quantity" class="form-control" placeholder="Please enter quantity *"  data-error="Quantity is required.">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_price">Price *</label>
                                    <input id="form_price" type="text" name="price" class="form-control" placeholder="Please enter the price *"  data-error="Valid number is required.">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <input type="submit" class="btn btn-success btn-send" >
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p class="text-muted"><strong>*</strong> These fields are required.</p>
                            </div>
                        </div>
                    </div>

                </form>

            </div>

        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h1>List of Products</h1>
                <table class="table table-striped" id="product_table">
                    <thead class="text-primary">
                    <tr>
                        <th>Product name</th>
                        <th>Quantity</th>
                        <th>Price per unit</th>
                    </tr>

                    </thead>
                    <tbody id="mydata">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop

resources/views/product-ajax.blade.php
@extends("ajax-master")

@section("content")
    <div class="container">
        <div class="row main">
            <div class="main-login main-center">
                <h5>Sign up once and watch any of our free demos.</h5>
                <form class="" method="post" action="{{URL::to('storeProduct')}}"  id="myForm">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label for="name" class="cols-sm-2 control-label">Name</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" name="name" id="name"  placeholder="Name"/>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="cols-sm-2 control-label">Description</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" name="email" id="email"  placeholder="Description"/>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="username" class="cols-sm-2 control-label">Price</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                                <input type="text" class="form-control" name="username" id="username"  placeholder="Price"/>
                            </div>
                        </div>
                    </div>



                    <div class="form-group ">
                        <button  type="submit" id="button" class="btn btn-primary btn-lg btn-block login-button">Register</button>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <script>
        $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
        $("#myForm").submit(function(event) {
//            return false;
            /* stop form from submitting normally */
            event.preventDefault();
            $.ajax({
                url: "{{URL::to('storeProduct')}}",
                dataType: 'json',
                type: 'post',
                //contentType: 'application/x-www-form-urlencoded',
                //headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                //headers: {'X-CSRF-TOKEN': "{{csrf_field()}}"},
                data: $("#myForm").serialize(),
                success: function( data){
                   console.log(data);
                },
                error: function( jqXhr, textStatus, errorThrown ){
                    console.log( errorThrown );
                }
            });

        });

    </script>
@stop